artifacts_root: artifacts

data_ingestion:
  root_directory: artifacts/data_ingestion
  local_data_file: artifacts/data_ingestion/DataSet.zip
  unzip_dir: artifacts/data_ingestion
  bucket_name: cnndataset1
  bucket_file_name: TomJerryData.zip

prepare_base_model:
  root_dir: artifacts/prepare_base_model
  base_model_path: artifacts/prepare_base_model/base_model.h5
  updated_base_model_path: artifacts/prepare_base_model/base_model_update.h5


